# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Swiss Jekyll Theme
description: A bold typographic theme inspired by Swiss design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: jekyll # the GitHub repo name for your project
github_username: jekyll

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jekyllrb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, yellow or custom.
theme_color: black

# colors for custom theme
color_background: "#2E86AB"
color_dot_accent: "#F6B042"
color_foreground: "#9C27B0"
color_title: "#E74C3C"
color_body_text: "#2ECC71"
color_text_accent: "#8E44AD"
color_code: "#F39C12"
color_nav_link: "#16A085"
color_primary_link: "#C0392B"

# Build settings
markdown: kramdown
